apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakarta-traffic-deployment
  labels:
    app: jakarta-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakarta-traffic
  template:
    metadata:
      labels:
        app: jakarta-traffic
    spec:
      containers:
      - name: jakarta-traffic-container
        image: tusharadelkar/jakarta-traffic-analysis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: jupyter-port
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        hostPath:
          path: /run/desktop/mnt/host/c/work/ai_compute/smart-trafic-analysis/data   # Docker Desktop WSL2 mount path
          type: DirectoryOrCreate
