apiVersion: v1
kind: Service
metadata:
  name: jakarta-traffic-service
  labels:
    app: jakarta-traffic
spec:
  type: NodePort
  selector:
    app: jakarta-traffic
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088   # Access the Jupyter server via http://<node-ip>:30088
    name: jupyter
